name: Windows - Anydesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download Files to Desktop
        run: |
          # Download VLC
          $vlcUrl = "https://get.videolan.org/vlc/3.0.21/win32/vlc-3.0.21-win32.exe"
          $vlcPath = "C:\Users\runneradmin\Desktop\vlc-3.0.21-win32.exe"
          Invoke-WebRequest -Uri $vlcUrl -OutFile $vlcPath
          
          # Download Google Drive File for Wallpaper
          $fileId = "18XultT1S-fEYUbWkh6FHjqz8aMJBsHrQ"
          $wallpaperPath = "C:\Users\runneradmin\Desktop\wallpaper.jpg"
          $url = "https://drive.google.com/uc?export=download&id=$fileId"
          Invoke-WebRequest -Uri $url -OutFile $wallpaperPath

      - name: Set Wallpaper
        run: |
          $wallpaperPath = "C:\Users\runneradmin\Desktop\wallpaper.jpg"
          $regKey = "HKCU:\Control Panel\Desktop"
          Set-ItemProperty -Path $regKey -Name "Wallpaper" -Value $wallpaperPath
          Set-ItemProperty -Path $regKey -Name "WallpaperStyle" -Value 2  # Centered
          Set-ItemProperty -Path $regKey -Name "TileWallpaper" -Value 0  # No tiling
          RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters

      - name: Create Credits.txt File
        run: |
          $creditsPath = "C:\Users\runneradmin\Desktop\Credits.txt"
          $creditsContent = "Modified By Daniel 64 Made with ChatGPT"
          Set-Content -Path $creditsPath -Value $creditsContent

      - name: Install AnyDesk
        run: |
          $anydeskUrl = "https://download.anydesk.com/AnyDesk.exe"
          $anydeskPath = "C:\Users\runneradmin\Desktop\AnyDesk.exe"
          Invoke-WebRequest -Uri $anydeskUrl -OutFile $anydeskPath
          Start-Process -FilePath $anydeskPath -ArgumentList "/install" -Wait

      - name: Auto Open Google Drive Link on Startup
        run: |
          $shortcutPath = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\AutoOpenDriveURL.lnk"
          $target = "C:\Windows\System32\cmd.exe"
          $arguments = "/c start https://drive.google.com/file/d/1POqArgjoK8VccM7McmZ4WPnDQF1ugKTs/view?usp=drivesdk"
          $wshShell = New-Object -ComObject WScript.Shell
          $shortcut = $wshShell.CreateShortcut($shortcutPath)
          $shortcut.TargetPath = $target
          $shortcut.Arguments = $arguments
          $shortcut.Save
